# Generated by Django 2.1.9 on 2019-06-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dboynum', models.IntegerField()),
                ('dgirlnum', models.IntegerField()),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eage', models.IntegerField()),
                ('egender', models.CharField(max_length=20)),
                ('ephoto', models.ImageField(upload_to='static/media')),
                ('epart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Departments')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['id'],
            },
        ),
    ]
